import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  containerLogo: {
    paddingTop: 50,
    marginTop: 60,
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    width: 550,
    height: 260,
    flexShrink: 0,
  },
  formTitle: {
    paddingStart: 10,
    marginBottom: 10,
    color: "#000",
    textAlign: "left",
    fontSize: 15,
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: 17,
    letterSpacing: -0.5,
  },
  formInput: {
    marginStart: 10,
    marginBottom: 10,
    width: "95%",
    height: 50,
    paddingVertical: 15,
    paddingHorizontal: 10,
    alignItems: "center",
    borderRadius: 3,
    borderWidth: 2,
    borderColor: "#73C74F",
    backgroundColor: "#DCDBDB",
    shadowColor: "#FF8A00",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 3,
  },
  formCheckBox: {
    width: "95%",
    paddingTop: 5,
    paddingStart: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 40,
  },
  subCheckBox: {
    flexDirection: "row",
    alignItems: "center",
  },
  checkbox: {
    width: 25,
    height: 25,
    flexShrink: 0,
    borderRadius: 3,
    marginRight: 5,
  },
  text: {
    color: "#000",
    textAlign: "center",
    fontSize: 14,
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: 17,
    letterSpacing: -0.5,
  },
  subForm: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: 3,
    paddingVertical: 15, // Padding vertical
    paddingHorizontal: 10, // Padding horizontal
  },
  formButton1: {
    backgroundColor: "#73C74F",
    justifyContent: "center",
    alignItems: "center",
    width: 190,
    height: 50,
  },
  formButton2: {
    width: 190,
    height: 50,
    backgroundColor: "#FDF7F7",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#000",
  },
  textButton1: {
    color: "#000",
    textAlign: "center",
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: 17,
    letterSpacing: -0.5,
  },
  textButton2: {
    color: "#73C74F",
    textAlign: "center",
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: 17,
    letterSpacing: -0.5,
  },
  subFormEmpresa: {
    margin: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  textEmpresa: {
    color: "#777",
    fontSize: 12,
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: 17, // Altura da linha em pixels
    letterSpacing: -0.5,
  },
})
