import { StyleSheet } from "react-native"
import {
  horizontalScale,
  moderateScale,
  verticalScale,
} from "../../components/Metrics"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  containerLogo: {
    paddingTop: verticalScale(50),
    marginTop: verticalScale(60),
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    width: horizontalScale(550),
    height: verticalScale(260),
    flexShrink: 0,
  },
  formTitle: {
    paddingStart: verticalScale(10),
    marginBottom: verticalScale(10),
    color: "#000",
    textAlign: "left",
    fontSize: moderateScale(15),
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: moderateScale(17),
    letterSpacing: -0.5,
  },
  formInput: {
    marginStart: horizontalScale(10),
    marginBottom: verticalScale(10),
    width: "95%",
    height: verticalScale(50),
    paddingVertical: verticalScale(15),
    paddingHorizontal: horizontalScale(10),
    alignItems: "center",
    borderRadius: 3,
    borderWidth: 2,
    borderColor: "#73C74F",
    backgroundColor: "#DCDBDB",
    shadowColor: "#FF8A00",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 3,
  },
  formCheckBox: {
    width: "95%",
    paddingTop: verticalScale(5),
    paddingStart: horizontalScale(10),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: verticalScale(40),
  },
  subCheckBox: {
    flexDirection: "row",
    alignItems: "center",
  },
  checkbox: {
    width: horizontalScale(25),
    height: verticalScale(25),
    flexShrink: 0,
    borderRadius: 3,
    marginRight: horizontalScale(5),
  },
  text: {
    color: "#000",
    textAlign: "center",
    fontSize: moderateScale(14),
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: moderateScale(17),
    letterSpacing: -0.5,
  },
  subForm: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: 3,
    paddingStart: horizontalScale(10),
    paddingEnd: horizontalScale(10),
  },
  formButton1: {
    backgroundColor: "#73C74F",
    justifyContent: "center",
    alignItems: "center",
    width: horizontalScale(170),
    height: verticalScale(48),
  },
  formButton2: {
    width: horizontalScale(170),
    height: verticalScale(48),
    backgroundColor: "#FDF7F7",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#000",
  },
  textButton1: {
    color: "#000",
    textAlign: "center",
    fontSize: moderateScale(16),
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: moderateScale(17),
    letterSpacing: -0.5,
  },
  textButton2: {
    color: "#73C74F",
    textAlign: "center",
    fontSize: moderateScale(16),
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: moderateScale(17),
    letterSpacing: -0.5,
  },
  subFormCompany: {
    marginVertical: verticalScale(70),
    alignItems: "center",
    justifyContent: "center",
  },
  textCompany: {
    color: "#777",
    fontSize: moderateScale(12),
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: moderateScale(17), // Altura da linha em pixels
    letterSpacing: -0.5,
  },
})
