import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  containerLogo: {
    paddingTop: "5.47vh",
    marginTop: "6.56vh",
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    width: "60vh",
    height: "28vh",
    flexShrink: 0,
  },
  formTitle: {
    paddingStart: "1vh",
    marginBottom: "1vh",
    color: "#000",
    textAlign: "left",
    fontSize: "1.6vh",
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: "1.85vh",
    letterSpacing: -0.5,
  },
  formInput: {
    marginStart: "1vh",
    marginBottom: "1vh",
    width: "95%",
    height: "5.47vh",
    paddingVertical: "1.85vh",
    paddingHorizontal: "1vh",
    alignItems: "center",
    borderRadius: 3,
    borderWidth: 2,
    borderColor: "#73C74F",
    backgroundColor: "#DCDBDB",
    shadowColor: "#FF8A00",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 3,
  },
  formCheckBox: {
    width: "95%",
    paddingTop: "0.5vh",
    paddingStart: "1vh",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "4.37vh",
  },
  subCheckBox: {
    flexDirection: "row",
    alignItems: "center",
  },
  checkbox: {
    width: "2.73vh",
    height: "2.73vh",
    flexShrink: 0,
    borderRadius: 3,
    marginRight: "0.5vh",
  },
  text: {
    color: "#000",
    textAlign: "center",
    fontSize: "1.53vh",
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: "1.85vh",
    letterSpacing: -0.5,
  },
  subForm: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: 3,
    paddingVertical: "2.5vh", // Padding vertical
    paddingHorizontal: "1.5vh", // Padding horizontal
  },
  formButton1: {
    backgroundColor: "#73C74F",
    justifyContent: "center",
    alignItems: "center",
    width: "20.5vh",
    height: "5.5vh",
  },
  formButton2: {
    width: "20.5vh",
    height: "5.5vh",
    backgroundColor: "#FDF7F7",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#000",
  },
  textButton1: {
    color: "#000",
    textAlign: "center",
    fontSize: "1.6vh",
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: "1.85vh",
    letterSpacing: -0.5,
  },
  textButton2: {
    color: "#73C74F",
    textAlign: "center",
    fontSize: "1.6vh",
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: "1.85vh",
    letterSpacing: -0.5,
  },
  subFormEmpresa: {
    margin: "4.37vh",
    alignItems: "center",
    justifyContent: "center",
  },
  textEmpresa: {
    color: "#777",
    fontSize: "1.2vh",
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: "1.85vh", // Altura da linha em vh
    letterSpacing: -0.5,
  },
})
